language: php
sudo: false

# PHP 5.4 and 5.5 are supported on a best-effort basis and are intentionally
# not included in the tested versions here, as the dependencies for the testing
# tools require newer versions of PHP.
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - TEST_TYPE=unit
  - TEST_TYPE=acceptance

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - env: TEST_TYPE=acceptance

cache:
    directories:
        - ./vendor

install:
    - composer self-update --no-interaction
    - composer install --dev --no-interaction

script:
    - if [ "${TRAVIS_PHP_VERSION}" != "7.0" ]; then ./vendor/bin/codecept run $TEST_TYPE; fi;
    - if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then ./vendor/bin/codecept run --coverage-xml $TEST_TYPE; fi;

after_success:
    - if [ -f ./tests/_output/coverage.xml ]; then travis_retry ./vendor/bin/coveralls -v; fi;
